### ISSUE TITLE
Access to the models [fully and 64-shot] fine-tuned on different datasets

### ISSUE THREAD

**Issue by ParishadBehnam** [facebookresearch/atlas#13]
Hi, 

We are trying to reproduce the generated answers of fully and 64-shot fine-tuned ATLAS on different datasets (including HotpotQA, as in Table 10 of the paper). However, we don't find checkpoints of the fine-tuned ATLAS on these datasets in the repository. Is there any way we can get access to them?

**Comment by mlomeli1** [comment]
hi @ParishadBehnam thank you for your interest. I am afraid there are no plans to release this, I am sorry.
