### ISSUE TITLE
Not able to download the NQ data

### ISSUE THREAD

**Issue by Tanya-11** [facebookresearch/atlas#16]
While following the instructions [here ](https://github.com/facebookresearch/atlas#getting-started-and-codebase-at-a-glance). I saw that I need to have `data/nq_data` in my `DATA_DIR`, but I don't see it after following the steps:
```
# download the NQ data
python preprocessing/prepare_qa.py --output_directory ${DATA_DIR} 
# download the Wikipedia 2018 corpus
python preprocessing/download_corpus.py --corpus corpora/wiki/enwiki-dec2018 --output_directory ${DATA_DIR} 
# downloads pretrained Atlas-large
python preprocessing/download_model.py --model models/atlas/${SIZE} --output_directory ${DATA_DIR} 
```
I only see following files/folders:
![image](https://github.com/facebookresearch/atlas/assets/90728105/23d15957-8396-4cf9-9c76-177c1b156abc)

Can you pls help me figure out, how can i download `nq_data`? Thanks!

**Comment by mlomeli1** [comment]
I just double checked this issue and it seems to work fine. If I run ` python preprocessing/prepare_qa.py --output_directory ${DATA_DIR}`, it correctly creates the `nq_data` folder, in L261 of `prepare_qa.py` creates the directory `nq_dir` in case it does not exist.
